feature_list_xgb =['period',
  'x_coordinate',
  'y_coordinate',
  'strength',
  'is_playoff',
  'game_time(s)',
  'prev_event_x',
  'prev_event_y',
  'time_since_prev_event',
  'is_rebound',
  'distance_to_prev_event',
  'speed_since_prev_event',
  'is_penalty_shot',
  'shot_distance',
  'shot_angle',
  'change_in_angle',
  'home_strength',
  'away_strength',
  'time_since_pp',
  'relative_strength',
  'shot_type_Backhand',
  'shot_type_Deflected',
  'shot_type_Slap Shot',
  'shot_type_Snap Shot',
  'shot_type_Tip-In',
  'shot_type_Wrap-around',
  'shot_type_Wrist Shot',
  'prev_event_type_Blocked Shot',
  'prev_event_type_Faceoff',
  'prev_event_type_Giveaway',
  'prev_event_type_Goal',
  'prev_event_type_Hit',
  'prev_event_type_Missed Shot',
  'prev_event_type_Penalty',
  'prev_event_type_Shot',
  'prev_event_type_Takeaway']

feature_list_lgbm = ['period',
  'x_coordinate',
  'y_coordinate',
  'strength',
  'is_playoff',
  'game_time(s)',
  'prev_event_x',
  'prev_event_y',
  'time_since_prev_event',
  'is_rebound',
  'distance_to_prev_event',
  'speed_since_prev_event',
  'is_penalty_shot',
  'shot_distance',
  'shot_angle',
  'change_in_angle',
  'home_strength',
  'away_strength',
  'time_since_pp',
  'relative_strength',
  'shot_type_Backhand',
  'shot_type_Deflected',
  'shot_type_Slap Shot',
  'shot_type_Snap Shot',
  'shot_type_Tip-In',
  'shot_type_Wrap-around',
  'shot_type_Wrist Shot',
  'prev_event_type_Blocked Shot',
  'prev_event_type_Faceoff',
  'prev_event_type_Giveaway',
  'prev_event_type_Goal',
  'prev_event_type_Hit',
  'prev_event_type_Missed Shot',
  'prev_event_type_Penalty',
  'prev_event_type_Shot',
  'prev_event_type_Takeaway']


feature_list_nn =['strength', 'is_playoff', 'time_since_prev_event', 'is_rebound',
        'distance_to_prev_event', 'speed_since_prev_event',
        'is_penalty_shot', 'shot_distance', 'shot_angle',
        'change_in_angle', 'time_since_pp', 'relative_strength',
        'shot_type_Backhand', 'shot_type_Deflected', 'shot_type_Slap Shot',
        'shot_type_Snap Shot', 'shot_type_Tip-In', 'shot_type_Wrap-around',
        'shot_type_Wrist Shot', 'prev_event_type_Blocked Shot',
        'prev_event_type_Faceoff', 'prev_event_type_Giveaway',
        'prev_event_type_Goal', 'prev_event_type_Hit',
        'prev_event_type_Missed Shot', 'prev_event_type_Penalty',
        'prev_event_type_Shot', 'prev_event_type_Takeaway']

feature_list_logreg =['shot_distance', 'shot_angle']

feature_list_stack_trained = ['period', 'x_coordinate', 'y_coordinate', 'strength',
        'game_time(s)', 'prev_event_x', 'prev_event_y',
        'time_since_prev_event', 'is_rebound', 'distance_to_prev_event',
        'speed_since_prev_event', 'shot_distance', 'shot_angle',
        'change_in_angle', 'home_strength', 'away_strength',
        'time_since_pp', 'relative_strength', 'shot_type_Backhand',
        'shot_type_Deflected', 'shot_type_Slap Shot',
        'shot_type_Snap Shot', 'shot_type_Tip-In', 'shot_type_Wrap-around',
        'shot_type_Wrist Shot', 'prev_event_type_Blocked Shot',
        'prev_event_type_Faceoff', 'prev_event_type_Giveaway',
        'prev_event_type_Goal', 'prev_event_type_Hit',
        'prev_event_type_Missed Shot', 'prev_event_type_Penalty',
        'prev_event_type_Shot', 'prev_event_type_Takeaway']

feature_list = ['period', 'x_coordinate', 'y_coordinate',
           'game_time(s)', 'prev_event_x', 'prev_event_y',
           'time_since_prev_event', 'is_rebound', 'distance_to_prev_event',
           'speed_since_prev_event', 'shot_distance', 'shot_angle',
           'change_in_angle', 'shot_type', 'prev_event_type','time_since_pp',
           'home_strength','away_strength', 'strength', 'relative_strength','is_penalty_shot', 'shot_type', 'is_playoff']